export const typography = {
  title:{
    f4xl:{
        fontSize:54,
        fontWeight:600
       },
       f3xl:{
        fontSize:42,
        fontWeight:600
       },
       fxxl:{
        fontSize:36,
        fontWeight:600
       },
       fxl:{
        fontSize:30,
        fontWeight:600
       },
       fl:{
        fontSize:24,
        fontWeight:600
       },
       fm:{
        fontSize:21,
        fontWeight:600
       },
       fs:{
        fontSize:17,
        fontWeight:600
       }, 
       fxs:{
        fontSize:15,
        fontWeight:600
       }
  },
  sub:{
       f3xl:{
        fontSize:30,
        fontWeight:400
       },
       fxxl:{
        fontSize:24,
        fontWeight:400
       },
       fxl:{
        fontSize:21,
        fontWeight:400
       },
       fl:{
        fontSize:18,
        fontWeight:400
       },
       fm:{
        fontSize:16,
        fontWeight:400
       },
       fs:{
        fontSize:14,
        fontWeight:400
       }, 
       fxs:{
        fontSize:13,
        fontWeight:400
       },
       fxs:{
        fontSize:11,
        fontWeight:400
       }
  },
  caps:{
      fl:{
        fontSize:15,
        fontWeight:400
       },
       fm:{
        fontSize:13,
        fontWeight:400
       },
       fs:{
        fontSize:11,
        fontWeight:400
       }, 
       fxs:{
        fontSize:10,
        fontWeight:400
       }
  },
  body:{
    fl:{
        fontSize:25,
        fontWeight:400,
        lineHeight:"25px",
        paraspace:"20px"
       },
       fm:{
        fontSize:14,
        fontWeight:400,
        lineHeight:"20px",
        paraspace:"15px"
       },
       fs:{
        fontSize:13,
        fontWeight:400,
        lineHeight:"18px",
        paraspace:"14px" 
       }, 
       fxs:{
        fontSize:11,
        fontWeight:400,
        lineHeight:"16px",
        paraspace:"12px"
       }
  }
}